# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d067839fdb2024800652b86e5eb16666a158d3ebc237e688d33bc9071d9e61a4c5aff9de909d7e989e6da660a5f41feb5ba4cf2bdb8d41452371ca158e81eadd

test:
  secret_key_base: 78630429454fd794916cc7e4e4c158d7ac0d6c8d0ac3da054dd7d828129f21755e02f2ee3af00dc0440b6c80907765b92d57d8372643076307ab890a91226f8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
